seeds.rb: deleted method <create_tests_by_user>, changes in <create_t…
Rezankozzi/TestGuru pull request #7
Opened 2022-05-20 11:04 UTC by Rezankozzi

…ests>; add to all models validations  end scopes.

2022-05-20 16:31 UTC, BubuntuClu requested changes

2022-05-20 16:31 UTC, BubuntuClu commented on app/models/question.rb
> +  def validate_number_of_answers
при сохранении ответа, не будут вызываться валидации вопроса. нужно валидацию перенести в модель ответов.
так же сделай так, чтобы валидация вызывалась только на метод `create`

2022-05-20 16:31 UTC, BubuntuClu commented on app/models/question.rb
> +    errors.add :base, :invalid, message: message unless (1..4).include?(answers.count)
нижнюю границу не стоит проверять. сделай просто не больше 4 услвоие

2022-05-20 16:31 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
`validates :title, presence: true, uniqueness: { scope: :level,
                                  message: 'test with this name and level already exists' }`

2022-05-20 16:31 UTC, BubuntuClu commented on db/seeds.rb
> -  def create_user_tests
зачем удалила создание пользователей? если я к себе выкачаю твою репу, то у меня сид пользователей не создаст

2022-05-20 16:31 UTC, BubuntuClu commented on db/seeds.rb
> +      test = Test.create title: test_title, category_id: id, level: rand(0..10), author_id: User.all.sample.id
1 - ты тут делаешь запрос за всеми пользователями, потом на 62 строке делаешь запрос за всеми пользователями. и там же на 62 строке делаешь запрос за всеми тестами, которые создаешь тут. много лишних запросов. сохраняй созданные объекты в переменные и используй их в коде, чтобы не напрягать БД лишний раз

2 - ставь скобки вокруг параметров метода. `Test.create(...)` `2.times { UserTest.create(user_id: user.id, test_id:... )`

2022-05-23 15:43 UTC, Rezankozzi commented on app/models/question.rb
> +  def validate_number_of_answers
я правильно понял: валидация должна вызываться при создании "лишнего"  ответа? То есть  он просто не будет сохранен в БД, если количество ответов на один вопрос превишает определенное число.?

2022-05-23 17:27 UTC, Rezankozzi commented on db/seeds.rb
> -  def create_user_tests
этом метод  перемещен на 60-65 строки.

2022-05-26 07:04 UTC, BubuntuClu commented on app/models/question.rb
> +  def validate_number_of_answers
да.
вопросы лучше в слак писать #aiidko
комментарии на гите не вижу

2022-05-26 07:05 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add :base, :invalid, message: message if question.answers.count > 4
ставь скобки вокруг параметров методов `errors.add(:base, :invalid, message: message)`
это как минимум плохая практика писать без них
как максимум можешь получить непредвиденное поведение

2022-05-26 16:10 UTC, merged